spring:
  ###################################################################################
  #  数据库连接
  datasource:
    username:
    password:
    url: https://192.168.10.10?gulimall-pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  ###################################################################################

###################################################################################
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
###################################################################################

###################################################################################
#内置tomcat
server:
  port: 10001
###################################################################################