spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.10:8848
  redis:
    host: 192.168.10.10
    port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
server:
  port: 20000

# 设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
